### ISSUE TITLE
Refactor GitHub OAuth WebFlow to use github-service API

### ISSUE THREAD

**Issue by ALRubinger** [redhat-developer-tooling/katapult#28]

**Comment by starksm64** [comment]
Assign to me

**Comment by ALRubinger** [comment]
Note that the current `GitHubServiceFactory` has:

```
public GitHubService create(final String githubUsername, final String personalAccessToken)
```

...and you're right now getting by with only the OAuth token:

```
.header("Authorization", "token " + accessToken)
```

...so you may want to overload `create` in the API and impl of the `GitHubServiceFactory` and `GitHubServiceLoader` to allow creation from only an OAuth token, or maybe you can also pass along the username in `GithubResource`.  Either way.

**Comment by starksm64** [comment]
Technically the username is not required when using an OAuth token. The underlying `org.kohsuke.github.GitHub` class allows a null when the OAuth token is passed in, in which case it uses the github api to resolve the user associated with the token, so a create from just an OAuth token is what I'll add.

The `GitHubService` interface also needs a create method for the creation of repositories to allow the current functionality of the `GithubResource` to rely on `GitHubService` .

**Comment by ALRubinger** [comment]
bdc4aafff391f18cee608e7940c0781094e3eb9b
87a66e484c2e03212b33d0f00575391a0d567e68
