### ISSUE TITLE
Error in GithubResourceIT

### ISSUE THREAD

**Issue by ALRubinger** [redhat-developer-tooling/katapult#33]
Using a GitHub account with 2-factor auth disabled (standard username/pass login).  Executed by: `mvn clean install -Pit` (Arquillian WildFly 10.0.0.Final Managed Adaptor)

Test fails with timeout:

```
should_fork_jboss_eap_quickstarts(org.rhd.katapult.test.services.GithubResourceIT)  Time elapsed: 98.85 sec  <<< ERROR!
com.gargoylesoftware.htmlunit.ScriptException: Exception invoking setHref
	at org.rhd.katapult.test.services.GithubResourceIT.should_fork_jboss_eap_quickstarts(GithubResourceIT.java:77)
Caused by: java.lang.RuntimeException: Exception invoking setHref
	at org.rhd.katapult.test.services.GithubResourceIT.should_fork_jboss_eap_quickstarts(GithubResourceIT.java:77)
Caused by: java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.1.107:8080 [/192.168.1.107] failed: connect timed out
	at org.rhd.katapult.test.services.GithubResourceIT.should_fork_jboss_eap_quickstarts(GithubResourceIT.java:77)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.1.107:8080 [/192.168.1.107] failed: connect timed out
	at org.rhd.katapult.test.services.GithubResourceIT.should_fork_jboss_eap_quickstarts(GithubResourceIT.java:77)
Caused by: java.net.SocketTimeoutException: connect timed out
	at org.rhd.katapult.test.services.GithubResourceIT.should_fork_jboss_eap_quickstarts(GithubResourceIT.java:77)
```

Server hangs here:
```
2016-04-07 17:37:50,511 INFO  [org.wildfly.extension.undertow] (ServerService Th
read Pool -- 24) WFLYUT0021: Registered web context: /katapult
2016-04-07 17:37:50,568 INFO  [org.jboss.as.server] (management-handler-thread -
 3) WFLYSRV0010: Deployed "application-ear.ear" (runtime-name : "application-ear
.ear")
2016-04-07 17:37:51,659 INFO  [org.rhd.katapult.github.GithubResource] (default 
task-1) Request to fork repository: jboss-developer/jboss-eap-quickstarts
2016-04-07 17:37:52,287 INFO  [org.rhd.katapult.github.GithubResource] (default 
task-1) OAuth2 response: Found
```

**Comment by ALRubinger** [comment]
The fork operation did succeed on the test account:
![screenshot4](https://cloud.githubusercontent.com/assets/199891/14367857/48671d0c-fce8-11e5-928a-e251664c3d97.png)

**Comment by ALRubinger** [comment]
Looks like hanging on an attempt to connect to a local host:

`org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.1.107:8080 [/192.168.1.107] failed: connect timed out`

I'm bound to:

```
[alr@overdrive ~]$ ifconfig |grep 192.168
        inet 192.168.2.60  netmask 255.255.255.0  broadcast 192.168.2.255
```

Some redirect to a local thing hardcoded somewhere?

**Comment by starksm64** [comment]
My github dev app that was referenced by the web.xml was using 192.168.1.107 as the ip in the callback url as my wildfly instance was bound to the interface, not localhost. I have updated the dev app to use a localhost callback url, so it should work now, but see the pull request I just put in for #27 that deals with the issue more generally.

**Comment by starksm64** [comment]
I had to install an openshift environment to run the integration tests. After that the tests are passing on a machine that does not have the 192.168.1.107 ip address.

[starksm@localhost katapult]$ ifconfig | grep inet
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:fdff:fe39:9590  prefixlen 64  scopeid 0x20<link>
        inet 172.16.156.148  netmask 255.255.255.0  broadcast 172.16.156.255
        inet6 fe80::20c:29ff:fe5b:487f  prefixlen 64  scopeid 0x20<link>
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        inet 192.168.124.1  netmask 255.255.255.0  broadcast 192.168.124.255

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] katapult-parent .................................... SUCCESS [  1.444 s]
[INFO] core-api ........................................... SUCCESS [  0.474 s]
[INFO] core-impl .......................................... SUCCESS [  0.055 s]
[INFO] github-service ..................................... SUCCESS [  3.629 s]
[INFO] openshift-service .................................. SUCCESS [  2.882 s]
[INFO] katapult ........................................... SUCCESS [  0.517 s]
[INFO] katapult-ear ....................................... SUCCESS [  0.453 s]
[INFO] tests .............................................. SUCCESS [ 16.642 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.507 s
[INFO] Finished at: 2016-04-07T22:05:48-07:00
[INFO] Final Memory: 34M/329M
[INFO] ------------------------------------------------------------------------

**Comment by ALRubinger** [comment]
Working for me now, but I'm unclear as to what changed as I don't see any code. :)

Are we relying on another component that's what the OAuth dev app is referencing: http://gitfork-jbossdev.rhcloud.com/api/github/callback ...?  Is this what you've changed?  If so, what's deployed here?

And is it not possible to have the callbackURL on the OAuth dev app configured in the GitHub UI directly link to "localhost"?

**Comment by starksm64** [comment]
The OAuth dev app that was hardcoded in this version was my GithubApiTesting app. It was it's callback url that I change to refer to localhost. We need two OAuth dev apps in the dev tool project; one that is for testing that uses a localhost based url, and one for the production deployment that uses whatever domain name the github service endpoint will be deployed under. When you merge the externalization pull request, you will need to specify which OAuth dev app you using in your environment.

**Comment by ALRubinger** [comment]
All setty.
